name: Creating automatic PR
on:
  push:
    branches:
      - main

jobs:
 main:
   name: Auto Merge
   runs-on: ubuntu-latest
   steps:
     - name: checking out code
       uses: actions/checkout@v3
       with:
          token: ${{ secrets.GH_TOKEN }}

    - name: create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "mramirezdev"
          pr_assignee: "mramirezdev"

     - name: enable automerge
        if: steps.pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pr_number }}
          merge-method: merge
